live_config_reload = true

import = [
    "~/.config/alacritty/iceberg-dark.toml"
]

[font]
size = 14
normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "Menlo", style = "Italic" }

[keyboard]
bindings = [
{ action = "ToggleSimpleFullscreen", key = "Enter", mods = "Command" },
{ action = "CreateNewWindow", key = "N", mods = "Command" },
{ chars = "]b", key = "{", mods = "Command|Shift" },
{ chars = "[b", key = "}", mods = "Command|Shift" },
]
