#!/bin/bash
#
# Split tmux pane.
#
# If the pane is wider than 2*minwidth then split it vertically. Otherwise split
# it horizontally

minwidth=70

width=$(tmux display-message -p '#{pane_width}')

if [[ $(echo "$width > 2*$minwidth" | bc) -eq 1 ]]; then
    tmux split-window -h
else
    tmux split-window -v
fi
